(("default" . ((user-emacs-directory . "~/.emacs.d")))
 ("spacemacs" . ((user-emacs-directory . "~/clones/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))))
 ("doom" . ((user-emacs-directory . "~/clones/doom-emacs")
            (env . (("DOOMDIR" . "~/.doom.d"))))))
