#!/usr/bin/env sh

alias cp="cp -i"     # confirm before overwriting something
alias mv="mv -i"     # confirm before overwriting something
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB
alias np='nano -w PKGBUILD'
alias mkdir="mkdir -p"
alias more=less

alias seti3="vim ~/.config/i3/config"

# apt aliases
if command -v apt >/dev/null; then
	alias sai='sudo apt install'
	alias sau='sudo apt update'
	alias sag='sudo apt upgrade'
fi

# Alias tmatrix
alias tmatrix="tmatrix -C red -s 10"

# Run emacs in CLI
# alias emacs="emacs -nw"

# Aliases for chezmoi
alias ch='    chezmoi'
alias cha='   chezmoi apply'

# Aliases for tmux
alias tn='    tmux new-session'
alias ta='    ~/scripts/tmux_attach_or_new.sh'
alias tks='   tmux kill-session -t'
alias tkss='  tmux kill-server'

alias pmx='   pulsemixer'
alias bctl='  bluetoothctl'
alias bch='   bluetoothctl connect 00:16:94:42:1B:8E'

# Aliases for emacsclient
alias ec='    emacsclient'
alias ecn='   emacsclient -n'  # Don't wait for the server to return
alias ect='   emacsclient -t'  # Open a new Emacs frame on the current terminal
alias eccn='  emacsclient -cn' # Create a new frame instead of trying to use the current Emacs frame
alias sec='   emacsclient -T /sudo:root@localhost:'
alias secn='  emacsclient -T /sudo:root@localhost: -n'
alias sect='  emacsclient -T /sudo:root@localhost: -t'
alias seccn=' emacsclient -T /sudo:root@localhost: -cn'

# Aliases for systemctl
alias si='  systemctl status'

alias sen=' sudo systemctl enable --now'
alias se='  sudo systemctl enable'
alias ss='  sudo systemctl start'
alias sdn=' sudo systemctl disable --now'
alias sd='  sudo systemctl disable'
alias st='  sudo systemctl stop'
alias sr='  sudo systemctl restart'

alias suen='sudo systemctl --user enable --now'
alias sue=' sudo systemctl --user enable'
alias sus=' sudo systemctl --user start'
alias sudn='sudo systemctl --user disable --now'
alias sud=' sudo systemctl --user disable'
alias sut=' sudo systemctl --user stop'
alias sur=' sudo systemctl --user restart'

alias winetricks='winetricks -q'

# === File managment === #
# alias ..='cd ..'
alias md=mkdir
alias rm.=' YEET=`pwd` && cd .. && gio trash "$YEET"'
alias dad=' dragon-drag-and-drop -x -a'

alias at='  atool'
alias atx=' atool -x'
alias ata=' atool -a'
alias ath=' atool -X .'

# Trash alias
alias rmt=' gio trash'

# Make a dir and slide in
mdcd() {
	mkdir $1 && cd $1
}

# Set up go-to-projects aliases if running bash. Use named directories in zsh
if [ -n "$BASH_VERSION" ]; then
	if [ -d "$HOME/Projects" ]; then
		alias cdp="cd $HOME/Projects"
	elif [ -d "$HOME/projects" ]; then
		alias cdp="cd $HOME/projects"
	fi
fi

# hostnamectl | grep "Operating System" | gawk 'match($0, /: (.+)/, os) {print os[1]}'
