#!/usr/bin/env sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# case $HOSTNAME in

# # PC
# nawordar-H81M-S1)
#     export EDITOR=vim
#     export TERMINAL=/usr/bin/xfce4-terminal
#     ;;

# # Notebook
# cezary-notebook)
#     export EDITOR=vim
#     export TERMINAL=/usr/bin/kitty
#     ;;
# esac

export EDITOR=nvim
export GIT_EDITOR="$EDITOR"
export TERMINAL=/usr/bin/kitty
export XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORMTHEME=gtk2
export MOZ_USE_XINPUT2=1

# Add TeX Live related variables
export TEXDIR="/usr/local/texlive/2020"
export TEXMFLOCAL="/usr/local/texlive/texmf-local"
export TEXMFSYSVAR="/usr/local/texlive/2020/texmf-var"
export TEXMFSYSCONFIG="/usr/local/texlive/2020/texmf-config"

export TEXMFVAR="$HOME/.texlive2020/texmf-var"
export TEXMFCONFIG="$HOME/.texlive2020/texmf-config"
export TEXMFHOME="$HOME/texmf"

# If emacs server is not opened, open it now
export ALTERNATE_EDITOR=''

# This kind of directory should always be hidden
export GOPATH="$HOME/.go"

if command -v dotnet >/dev/null; then
	# Add .Net to PATH Source: https://github.com/OmniSharp/omnisharp-vscode/issues/2970#issuecomment-541516806
	DOTNET_BASE=$(dotnet --info | grep "Base Path" | awk '{print $3}')
	DOTNET_ROOT=$(echo $DOTNET_BASE | sed -E "s/^(.*)(\/sdk\/[^\/]+\/)$/\1/")
	export MSBuildSDKsPath=${DOTNET_BASE}Sdks/
	export DOTNET_ROOT=$DOTNET_ROOT
fi

add_dir_to_path() {
	if [ -d "$1" ]; then
		export PATH="$1:$PATH"
	fi
}

# if running bash
if [ -n "$BASH_VERSION" ]; then
	# include .bashrc if it exists
	if [ -f "$HOME/.bashrc" ]; then
		. "$HOME/.bashrc"
	fi
fi

# set PATH so it includes user's private bin if it exists
add_dir_to_path "/bin"
add_dir_to_path "/usr/bin"
add_dir_to_path "/usr/local/bin"
add_dir_to_path "/usr/local/go/bin"
add_dir_to_path "/usr/local/texlive/2020/bin/x86_64-linux"
add_dir_to_path "/opt/miktex/bin"
add_dir_to_path "$HOME/bin"
add_dir_to_path "$HOME/.local/bin"
add_dir_to_path "$HOME/.cargo/bin"
add_dir_to_path "$HOME/.dotnet/tools"
add_dir_to_path "$HOME/clones/doom-emacs/bin"
add_dir_to_path "$HOME/clones/mxe/usr/bin"
add_dir_to_path "$DOTNET_ROOT"
add_dir_to_path "$(yarn global bin --offline)"
add_dir_to_path "$(go env GOPATH)/bin"
