user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("extensions.pocket.enabled"          , false);
user_pref("toolkit.telemetry.archive.enabled"  , false);
user_pref("toolkit.telemetry.enabled"          , false);
user_pref("toolkit.telemetry.prompted"         , 2    );
user_pref("toolkit.telemetry.rejected"         , true );
user_pref("toolkit.telemetry.rejected"         , true );
user_pref("toolkit.telemetry.server"           , ""   );
user_pref("toolkit.telemetry.unified"          , false);
user_pref("toolkit.telemetry.unifiedIsOptIn"   , false);
