alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias mkdir="mkdir -p"
alias more=less

alias seti3="vim ~/.config/i3/config"

# Ubuntu only aliases


hostnamectl | grep "Operating System" | gawk 'match($0, /: (.+)/, os) {print os[1]}'
